GET http://localhost:7000/api


### User register
POST localhost:7000/api/register
Content-Type: application/json

{
  "email" : "rustam2@gmail.com",
  "password" : "test1",
  "role" : "admin"
}

### Login
POST localhost:7000/api/login
Content-Type: application/json

{
  "email" : "test@gmail.com",
  "password" : "test1"
}

### Logout
POST localhost:7000/api/logout
Content-Type: application/json


### Admin
GET localhost:7000/api/admin
Content-Type: application/json

### Admin: Get players
GET localhost:7000/api/admin/players
Content-Type: application/json

### Admin: Get Player
GET localhost:7000/api/admin/players/66980cf412b91db82d831c62
Content-Type: application/json

### Admin: Add player
POST localhost:7000/api/admin/players
Content-Type: application/json

{
  "name": "Baadur Jobava",
  "age": 36,
  "rating": 2702,
  "country": "Gruziya"
}

### Admin: Delete Player
DELETE localhost:7000/api/admin/players
Content-Type: application/json

{
  "name": "Baadur Jobava"
}

### Admin: Update Player
PUT localhost:7000/api/admin/players/6698972dfd97f63bbd303b87
Content-Type: application/json

{
  "country": "Uzbekistan"
}

### Admin: Create Tournament
POST localhost:7000/api/admin/tournaments
Content-Type: application/json

{
  "name": "Winter Championship 2024",
  "startDate": "2024-08-01",
  "endDate": "2024-08-10",
  "participants": ["669803168da520e0107c14b5", "6698032f8da520e0107c14b7"]
}

### Admin: Add Players tournament
PUT localhost:7000/api/admin/tournaments/66989f27f3ac26b168cf7f8c
Content-Type: application/json

{
  "participants" : "669803998da520e0107c14cb"
}


### Create Round
POST localhost:7000/api/admin/round/6698f03a9728a4059af940c8
Content-Type: application/json

{
  "roundNumber" : 1
}

### Create Match
POST localhost:7000/api/admin/match/6698f0739728a4059af940cb
Content-Type: application/json

{
  "result" : "1-0"
}