### Root
GET http://localhost:7000/api

### User register
POST localhost:7000/api/register
Content-Type: application/json

{
  "email" : "string",
  "password" : "string",
  "role" : "admin || user"
}

### Login
POST localhost:7000/api/login
Content-Type: application/json

{
  "email" : "string",
  "password" : "string"
}

### Logout
## accesToken orqali
POST localhost:7000/api/logout
Content-Type: application/json


### Admin
## Admin root
GET localhost:7000/api/admin
Content-Type: application/json

### Admin: Get players
## Required: Admin role
GET localhost:7000/api/admin/players
Content-Type: application/json

### Admin: Get Player
## Required: player id
GET localhost:7000/api/admin/players/[:id]
Content-Type: application/json

### Admin: Add player
POST localhost:7000/api/admin/players
Content-Type: application/json

{
  "name": "Baadur Jobava",
  "age": 36,
  "rating": 2702,
  "country": "Gruziya"
}

### Admin: Delete Player
## Required: player name
DELETE localhost:7000/api/admin/players
Content-Type: application/json

{
  "name": "Baadur Jobava"
}

### Admin: Update Player
## Required: player id
PUT localhost:7000/api/admin/players/[:id]
Content-Type: application/json

{
  "country": "Uzbekistan"
}

### Admin: Create Tournament
POST localhost:7000/api/admin/tournaments
Content-Type: application/json

{
  "name": "Winter Championship 2024",
  "startDate": "2024-08-01",
  "endDate": "2024-08-10",
  "participants": ["669803168da520e0107c14b5", "6698032f8da520e0107c14b7"]
}

### Admin: Add Players tournament
## Required: tournaments id
PUT localhost:7000/api/admin/tournaments/[:id]
Content-Type: application/json

{
  "participants" : "669803998da520e0107c14cb"
}


### Create Round
# Required:  turnir id
POST localhost:7000/api/admin/round/[:id]
Content-Type: application/json

{
  "roundNumber" : 2
}

### Create Match
# Required: round id
POST localhost:7000/api/admin/match/[:id]
Content-Type: application/json

{
  "result" : "1/2-1/2 || 1-0 || 0-1"
}

### Lidearboard
# Required: turnit id
GET localhost:7000/api/admin/match/liderboard/[:id]
Content-Type: application/json