GET http://localhost:7000/api


### User register
POST localhost:7000/api/register
Content-Type: application/json

{
  "email" : "rustam2@gmail.com",
  "password" : "test1",
  "role" : "admin"
}

### Login
POST localhost:7000/api/login
Content-Type: application/json

{
  "email" : "test@gmail.com",
  "password" : "test1"
}

### Logout
POST localhost:7000/api/logout
Content-Type: application/json


### Admin
GET localhost:7000/api/admin
Content-Type: application/json

### Admin: Get players
GET localhost:7000/api/admin/player
Content-Type: application/json

### Admin: Get Player
GET localhost:7000/api/admin/player/669803998da520e0107c14cb
Content-Type: application/json

### Admin: Add player
POST localhost:7000/api/admin/player
Content-Type: application/json

{
  "name": "Baadur Jobava",
  "age": 36,
  "rating": 2702,
  "country": "Gruziya"
}

### Admin: Delete Player
DELETE localhost:7000/api/admin/user
Content-Type: application/json

{
  "email" : "deko@gmail.com"
}